name: Build TinaCMS Starter Templates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'

jobs:
  build-templates:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        package-manager: [yarn, npm, pnpm]
        template:
          - tina-cloud-starter
          - tina-hugo-starter
          - tina-remix-starter
          - demo-docs
          - tinasaurus
          - basic
        node-version: [18, 20, 22]
    outputs:
      failed: ${{ steps.report-errors.outputs.failed }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
        if: ${{ matrix.package-manager == 'pnpm' }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
        if: ${{ matrix.template == 'tina-hugo-starter' }}

      - name: Run create-tina-app
        run: npx create-tina-app@latest template-repo --pkg-manager ${{ matrix.package-manager }} --template ${{ matrix.template }}

      - name: Run build
        run: |
          cd template-repo
          ${{ matrix.package-manager }} install && ${{ matrix.package-manager }} run build-local

      - name: Report errors
        continue-on-error: false
        id: report-errors
        if: failure()
        run: |
          ISSUE_TITLE="Starter template '${{ matrix.template }}' failed to build with ${{ matrix.package-manager }}"
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          echo "failed=true" >> "$GITHUB_OUTPUT"

          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          if gh issue list --state open --limit 100 --search "$ISSUE_TITLE" | grep -q "$ISSUE_TITLE"; then
            echo "Issue already exists. Skipping issue creation."
          else
            echo "Creating a new issue..."
            gh issue create --title "$ISSUE_TITLE" \
              --body "The **${{ matrix.template }}** starter template failed to build using **${{ matrix.package-manager }}**.\n\nCheck the full workflow logs for more details: [View Workflow Run]($RUN_URL)" \
              --labels "bug"
          fi

  check-failures:
    needs: build-templates
    runs-on: ubuntu-latest
    steps:
      - name: Check if any job failed
        run: |
          if [[ "${{ needs.build-templates.outputs.failed }}" == "true" ]]; then
            echo "One or more commands failed."
            exit 1
          else
            echo "All commands succeeded."
          fi
