name: Compressed Size Diff

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tinacms/compressed-size-action@master
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          install-script: 'npm run ci'
          pattern: '{**/dist/**/*.js,**/build/**/*.js}'
          collapse-unchanged: true
          show-total: true
