name: Compressed Size Diff

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: preactjs/compressed-size-action@v1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '{**/dist/*.js,**/build/*.js}'
          build-script: 'bootstrap && npm run build'
