name: 'Danger JS'
on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm ci
      - name: Danger
        uses: danger/danger-js@10.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
