name: e2e Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.5.0-chrome94-ff93
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install --immutable --immutable-cache
          browser: chrome
          env: NEXT_PUBLIC_USE_LOCAL_CLIENT=1
          build: yarn build:e2e
          command: yarn test:e2e
          start: yarn start:e2e
          wait-on: 'http://localhost:3000'
          # wait for 3 minutes for the server to respond
          wait-on-timeout: 180
