name: e2e Tests

on: [push]

jobs:
  cypress-run-ubuntu:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.5.0-chrome94-ff93
    name: E2E Tests
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.0
          run_install: true

      - name: Install dependencies
        run: pnpm install

      - name: Build E2E
        run: pnpm build:e2e

      - name: Start E2E
        run: pnpm start:e2e &
        env:
          NEXT_PUBLIC_USE_LOCAL_CLIENT: 1

      - name: Wait on http://localhost:3000
        run: npx wait-on http://localhost:3000 --timeout 180000

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          start: false
          wait-on: false
        env:
          NEXT_PUBLIC_USE_LOCAL_CLIENT: 1

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
