name: e2e Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - name: check the file list
        run: |
          ls -la examples/basic/.tina/__generated__/  # list the files for confirmation.
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install --immutable --immutable-cache
          browser: chrome
          env: NEXT_PUBLIC_USE_LOCAL_CLIENT=1
          build: yarn build
          command: yarn cypress run
          start: yarn workspace starter-basic dev 
          wait-on: 'http://localhost:3000'
          # wait for 3 minutes for the server to respond
          wait-on-timeout: 180
