name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap Dependencies
      run: npm run bs
    - name: Run a multi-line script
      run: lerna run test --parallel
