name: Build, Test, Lint

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install
        run: |
          npm ci
          npm run bs

      - name: Build
        run: npm run build
  test:
    runs-on: macOS-latest
    needs: build
    steps:
      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint
