name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm i
    - name: Bootstrap Development
      run: npm run bs
    - name: Run a multi-line script
      run: ./bin/lerna run test --parallel
