name: Build, Test, Lint for Main

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        #  - windows-latest
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - if: matrix.os == 'windows-latest'
        run: |
          yarn add windows-build-tools@4.0.0
          yarn add node-gyp
      - name: Install
        run: yarn install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: yarn lint

      - name: Build Types
        run: yarn types
