name: Build, Test, Lint

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - if: matrix.os == 'windows-latest'
        run: |
          npm install --global --production windows-build-tools@4.0.0
          npm install --global --production node-gyp

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: |
          npm ci
          npm run bs

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint
