name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Bootstrap Development
        run: npm run bs
      - name: Lint Source Coude
        run: npm run lint
      - name: Build Packages
        run: npm run build
      - name: Run Tests
        run: npm run test
