name: Publish
on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        channel:
          - latest
          - dev

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Install dependencies
        # Before merging to main, re-run the install for security purposes
        # https://yarnpkg.com/features/zero-installs/#does-it-have-security-implications
        run: yarn install --check-cache
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Release to @dev channel
        if: matrix.channel == 'dev'
        run: |
          yarn version:snapshot
          yarn publish:beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        if: matrix.channel == 'latest'
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Create release pull request
        uses: changesets/action@master
        if: matrix.channel == 'latest'
        with:
          version: yarn version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
