name: Publish PRs
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'PR Number'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Install dependencies
        # Before merging to main, re-run the install for security purposes
        # https://yarnpkg.com/features/zero-installs/#does-it-have-security-implications
        run: yarn install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build
        run: yarn build
      # - name: Test
      #   run: yarn test
      # - name: Build Types
      #   run: yarn types
      - name: Publish under PR tag
        run: |
          echo running on branch ${GITHUB_REF##*/}
          yarn version:snapshot
          yarn workspaces foreach --no-private --verbose npm publish --tolerate-republish --tag ${GITHUB_REF##*/} --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
